---
- name: Prereq Disable Firewalld, SELinux, Multipath, and Swap
  hosts: master,masterHA,worker
  become: true

  tasks:
    - name: Disable Firewalld
      systemd:
        name: ufw
        enabled: no
        state: stopped

    - name: Disable Multipath
      systemd:
        name: multipathd
        enabled: no
        state: stopped

    - name: Disable Swap
      ansible.builtin.mount:
        path: swap
        state: absent
    - name: Create /var/log/kubernetes directory
      ansible.builtin.file:
        path: /var/log/kubernetes
        state: directory

    - name: Create /var/log/kubernetes/audit directory
      ansible.builtin.file:
        path: /var/log/kubernetes/audit
        state: directory

    - name: Create /var/lib/rancher directory
      ansible.builtin.file:
        path: /var/lib/rancher/
        state: directory

    - name: Create /var/lib/rancher/k3s directory
      ansible.builtin.file:
        path: /var/lib/rancher/k3s
        state: directory

    - name: Create /var/lib/rancher/k3s/server directory
      ansible.builtin.file:
        path: /var/lib/rancher/k3s/server
        state: directory

    - name: Create /var/lib/rancher/k3s/server/manifests directory
      ansible.builtin.file:
        path: /var/lib/rancher/k3s/server/manifests
        state: directory

    - name: Create audit.yaml file
      ansible.builtin.copy:
        content: |
          apiVersion: audit.k8s.io/v1 
          kind: Policy
          rules:
            - level: Metadata
        dest: /var/lib/rancher/k3s/server/manifests/audit.yaml


- name: Install K3S on master
  hosts: master
  become: true
  gather_facts: false

  vars_files:
    - /srv/ansible/playbook-k3s/ansible-vars.yml

  tasks:
    - name: Get Load Balancer Hostname from Inventory
      set_fact:
        load_balancer_hostname: "{{ hostvars[groups['lb'][0]].inventory_hostname }}"
    - name: Check if kubectl is installed
      command: "which kubectl"
      register: kubectl_installed
      ignore_errors: true

    - name: Check if k3s is installed
      command: "which k3s"
      register: k3s_installed
      ignore_errors: true

    - name: Echo kubectl Installation Status
      debug:
        var: kubectl_installed.rc

    - name: Echo k3s Installation Status
      debug:
        var: k3s_installed.rc

    - name: Echo loadbalance-hostname
      debug:
        var: load_balancer_hostname

    - name: Run K3S Installation Script master
      shell:  "{{ k3s_installation_script_master }}"
      register: k3s_installation_result
      changed_when: k3s_installation_result.stdout is not none
      when: kubectl_installed.rc != 0 or k3s_installed.rc != 0

    - name: Wait for node to be ready
      become: yes
      ansible.builtin.shell: $([[ $(kubectl get node $(cat /etc/hostname) -o jsonpath='{.status.conditions[?(@.type=="Ready")].status}') == "True" ]])
      args:
        executable: /bin/bash
      register: kubelet_ready
      until: kubelet_ready.rc == 0
      retries: 60
      delay: 3

    - name: Change file access node-token
      file:
        path: /var/lib/rancher/k3s/server
        mode: "g+rx,o+rx"
      run_once: yes
    - name: Read node-token from master
      slurp:
        src: /var/lib/rancher/k3s/server/node-token
      register: node_token
      run_once: yes

    - name: Store Master node-token
      set_fact:
        k3s_token: "{{ node_token.content | b64decode | regex_replace('\n', '') }}"
      run_once: yes
    - name: Echo Token Result master
      debug:
        var: k3s_token

- name: Install K3S on subsequent master nodes
  hosts: masterHA
  become: true
  gather_facts: false

  vars_files:
    - /srv/ansible/playbook-k3s/ansible-vars.yml

  tasks:
    - name: Get Load Balancer Hostname from Inventory
      set_fact:
        load_balancer_hostname: "{{ hostvars[groups['lb'][0]].inventory_hostname }}"

    - name: Check if kubectl is installed
      command: "which kubectl"
      register: kubectl_installed
      ignore_errors: true

    - name: Check if k3s is installed
      command: "which k3s"
      register: k3s_installed
      ignore_errors: true

    - name: Echo kubectl Installation Status
      debug:
        var: kubectl_installed.rc

    - name: Echo k3s Installation Status
      debug:
        var: k3s_installed.rc
    - name: Set Token Fact for masterHA
      set_fact:
        k3s_token: "{{ hostvars[groups['master'][0]].k3s_token }}"
    - name: Run K3S Installation Script MasterHA
      shell: "{{ k3s_installation_script_masterHA }}"
      register: k3s_installation_result
      changed_when: k3s_installation_result.stdout is not none
      when: kubectl_installed.rc != 0 or k3s_installed.rc != 0

    - name: Wait for node to be ready
      become: yes
      ansible.builtin.shell: $([[ $(kubectl get node $(cat /etc/hostname) -o jsonpath='{.status.conditions[?(@.type=="Ready")].status}') == "True" ]])
      args:
        executable: /bin/bash
      register: kubelet_ready
      until: kubelet_ready.rc == 0
      retries: 60
      delay: 3

- name: Install K3S agent  on worker nodes
  hosts: worker
  become: true
  gather_facts: false
  vars_files:
    - /srv/ansible/playbook-k3s/ansible-vars.yml

  tasks:
    - name: Get Load Balancer Hostname from Inventory
      set_fact:
        #load_balancer_hostname: "{{ hostvars['loadbalancer'].inventory_hostname }}"
        load_balancer_hostname: "{{ hostvars[groups['lb'][0]].inventory_hostname }}"
    - name: Set Token Fact for Workers
      set_fact:
        k3s_token: "{{ hostvars[groups['master'][0]].k3s_token }}"
    - name: Check if kubectl is installed
      command: "which kubectl"
      register: kubectl_installed
      ignore_errors: true

    - name: Check if k3s is installed
      command: "which k3s"
      register: k3s_installed
      ignore_errors: true

    - name: Echo kubectl Installation Status
      debug:
        var: kubectl_installed.rc

    - name: Echo k3s Installation Status
      debug:
        var: k3s_installed.rc

    - name: Run K3S Installation Script worker
      shell: "{{ k3s_installation_script_worker }}"
      register: k3s_installation_result
      changed_when: k3s_installation_result.stdout is not none
      when: kubectl_installed.rc != 0 or k3s_installed.rc != 0
