---
- name: Install Docker on Alpine Linux
  hosts: loadbalancer
  become: true
  become_method: doas  # Use doas instead of sudo
  
  tasks:
    - name: Update package index
      community.general.apk:
        update_cache: yes
    
    - name: Update repositories and install docker package
      community.general.apk:
        name: docker
        update_cache: true

    - name: Create /etc/nginx.conf file
      ansible.builtin.template:
        src: /srv/k3s-ansible/playbook/j2/nginx.conf.j2
        dest: /etc/nginx.conf
      notify: Restart Docker
  handlers:
    - name: Restart Docker
      ansible.builtin.service:
        name: docker
        state: restarted

    - name: Install required Python library (requests)
      ansible.builtin.apk:
        name: py3-requests  # This may vary based on your Alpine Linux version
        state: present

    - name: Run Nginx Docker container
      ansible.builtin.docker_container:
        name: nginx_container
        image: nginx:1.14
        detach: true
        restart_policy: unless-stopped
        ports:
          - "6443:6443"
          - "443:443"
          - "8080:8080"
        volumes:
          - "/etc/nginx.conf:/etc/nginx/nginx.conf"

