- name: apt-update on all Ubuntu nodes
  hosts: k3s_cluster
  become: yes
  tasks:
    - name: apt
      apt:
        update_cache: yes
        upgrade: 'yes'

## install kubectl on alpine1
- name: Update kubeconfig
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Install curl
      become: yes
      apk:
        name: curl
        state: present
    - name: Install collection community.general
      community.general.ansible_galaxy_install:
        type: collection
        name: community.general
    - name: Update repositories and install kubectl package
      become: yes
      community.general.apk:
        name: kubectl
        update_cache: true
        repository: http://dl-cdn.alpinelinux.org/alpine/edge/community
