- name: Update search domain
  hosts: master*,worker
  become: true

  tasks:
    - name: Add k8s.lab to search domain
      lineinfile:
        path: /etc/netplan/00-installer-config.yaml
        regexp: '^\s+search: \[.*\]'
        line: '        search: ["k8s.lab"]'
      become: true
    - name: Apply Netplan configuration
      become: true
      become_method: sudo
      command: netplan apply

