---
- name: Merge kubeconfig files
  hosts: localhost
  gather_facts: no
  vars:
    kubeconfig_dir: /root/.kube/clusters
    merged_kubeconfig_path: /root/.kube/merged_kubeconfig
    kubeconfig_files: "{{ lookup('fileglob', kubeconfig_dir + '/*.yaml').split(',') }}"
  tasks:    
  
    - name: Find files in /root/.kube/clusters directory
      ansible.builtin.find:
        paths: "/root/.kube/clusters"
        file_type: file
      register: kubeconfig_files

    - name: Display found files
      ansible.builtin.debug:
        #var: kubeconfig_files.files.path
        msg: "{{ kubeconfig_files.files | map(attribute='path') | list }}"

    - name: Create a temporary directory
      ansible.builtin.file:
        path: /tmp/kubeconfig_temp
        state: directory

    - name: Find kubeconfig files
      ansible.builtin.find:
        paths: "{{ kubeconfig_dir }}"
        file_type: file
        patterns: "*.yaml"
      register: kubeconfig_files

    # - name: Concatenate files
    #   ansible.builtin.shell: 
    #     cmd: cat "{{ item.path }}" >> /tmp/kubeconfig_temp/merged_kubeconfig
    #   with_items: "{{ kubeconfig_files.files }}"
    #   loop_control:
    #     label: "{{ item.path }}"
    - name: Add KUBECONFIG path to shell configuration file
      ansible.builtin.lineinfile:
        path: "~/.bashrc"  # Specify the shell configuration file you want to modify
        line: "export KUBECONFIG=$KUBECONFIG:/root/.kube/clusters/*"
        create: yes  # Create the file if it does not exist




    - name: Debug file names
      ansible.builtin.debug:
        msg: "Processing file {{ item.path }}"
      loop: "{{ kubeconfig_files.files }}"
    
    - name: Copy merged kubeconfig to the destination
      ansible.builtin.copy:
        src: /tmp/kubeconfig_temp/merged_kubeconfig
        dest: "{{ merged_kubeconfig_path }}"
        remote_src: yes
        mode: '0600'

    - name: Clean up temporary directory
      ansible.builtin.file:
        path: /tmp/kubeconfig_temp
        state: absent

