---
- name: Undo cluster setup
  hosts: master,masterHA,worker
  become: true
  tasks:
    - name: Run K3s Uninstall script [server]
      when: "'master' in group_names or 'masterHA' in group_names" 
      ansible.builtin.command:
        cmd: /usr/local/bin/k3s-uninstall.sh
        removes: /var/lib/rancher/k3s/*
    - name: Run K3s Uninstall script [agent]
      when: "'worker' in group_names"
      ansible.builtin.command:
        cmd: /usr/local/bin/k3s-agent-uninstall.sh
        removes: /var/lib/rancher/k3s/*
    - name: Remove user kubeconfig
      ansible.builtin.file:
        path: /home/{{ ansible_user }}/.kube/config
        state: absent
