site_name: k3s-lab-setup
site_url: https://example.com/
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  #name: ivory
  #custom_dir: overrides
# nav:
#     - Home: index.md
#     - Article: 001-Hyper-V-Host-Specification.md
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
nav:
  - Get started:
      - index.md
      - ReadMe.md
  - Prerequisites:
      - 000-Prerequisites/001-Hyper-V-Host-Specification.md
      - 000-Prerequisites/002-High-Level-node-setup.md
      - 000-Prerequisites/002-vi-basics.md
      - 000-Prerequisites/003-clone-repository.md
      - 000-Prerequisites/004-Hyper-V-VM-creation.md
  - Management Server alpine1 setup:
      - 100-alpine1\100-alpine1-setup.md
      #- 100-alpine1\1000-Clone-repository (copy).md
      - 100-alpine1\101-ssh-to-alpine1.md
      - 100-alpine1\102-Clone-repository.md
      #- 100-alpine1\103-setup-using-ansible-manual.md
      - 100-alpine1\103-setup-using-ansible.md
      - Setup services Manual Steps:
                - 100-alpine1\manual-steps\101-DHCP-server.md
                - 100-alpine1\manual-steps\102-setup-router.md
                - 100-alpine1\manual-steps\103-setup-dns.md
                - 100-alpine1\manual-steps\104-setup-nginx.md
                - 100-alpine1\manual-steps\105-nfs.md
                - 100-alpine1\manual-steps\106-tftp.md
                - 100-alpine1\manual-steps\107-cloud-init.md
                - 100-alpine1\manual-steps\108-DHCP-for-PXE.md
                - 100-alpine1\manual-steps\109-setup-boot-files-part1-PXE.md
                - 100-alpine1\manual-steps\110-setup-boot-files-part2-OS.md
                - 100-alpine1\manual-steps\111-setup-boot-files-part3-pxelinux.cfg.md
                #- 100-alpine1\manual-steps\112-New-single-VM-setup-Ubuntu-autoinstall.md
                - 100-alpine1\manual-steps\113-generate-user-data-multipleVM.md
      #- 100-alpine1\104-Validation.md
      - Ubuntu Installation: 100-alpine1\113-Install-Ubuntu.md
  - Lightweight Kubernetes Installation:
      - 200-kubernetes\200-ReadMe.md
      - 200-kubernetes\201-SSH-keys-setup.md
      - 200-kubernetes\202-Setup-k3s-with-Ansible.md
      - 200-kubernetes\204-k3s-setup-complete.md
      - 200-kubernetes\manual-steps\202-Ansible-inventory.md
      - 200-kubernetes\manual-steps\203-Setup-k3s-with-Ansible.md
        # - 900-Explainers\PXELINUX.md
        # - 900-Explainers\generate-user-data-multipleVM.md
        # - 900-Explainers\generate-user-data-reference.md