---
- name: Configure IP forwarding and enable IP routing on alpine1
  hosts: alpine1
  become: true
  tasks:
    - name: Enable IP forwarding in sysctl.conf
      lineinfile:
        path: /etc/sysctl.conf
        line: "net.ipv4.ip_forward=1"
      notify: Reload sysctl.conf

    - name: Install iptables package
      apk:
        name: iptables
        state: present

    - name: Add iptables service to startup
      command: rc-update add iptables default

    - name: Allow forwarding from eth1
      iptables:
        chain: FORWARD
        in_interface: eth1
        jump: ACCEPT

    - name: Enable NAT for eth0
      iptables:
        table: nat
        chain: POSTROUTING
        out_interface: eth0
        jump: MASQUERADE

    - name: Save iptables rules
      command: /etc/init.d/iptables save
      notify: Restart iptables service

  handlers:
    - name: Reload sysctl.conf
      command: sysctl -p

    - name: Restart iptables service
      service:
        name: iptables
        state: restarted
