---
- name: Deploy Nginx using Docker
  hosts: localhost
  tasks:
    - name: Install Docker dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

    - name: Add Docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update APT package cache
      apt:
        update_cache: yes

    - name: Install Docker CE
      apt:
        name: docker-ce
        state: present

    - name: Install Docker Compose
      pip:
        name: docker-compose
        state: present

    - name: Copy Nginx Docker Compose file
      copy:
        src: nginx-docker-compose.yml
        dest: /path/to/nginx-docker-compose.yml

    - name: Set permissions for Docker Compose file
      file:
        path: /path/to/nginx-docker-compose.yml
        mode: '0644'

    - name: Start Nginx container
      command: docker-compose -f /path/to/nginx-docker-compose.yml up -d
