---
- name: Configure Cloud-init on localhost
  hosts: localhost
  become: true
  tasks:
    - name: Enable community repository
      lineinfile:
        path: /etc/apk/repositories
        regexp: '^#http://mirror.jingk.ai/alpine/v3.18/community'
        line: 'http://mirror.jingk.ai/alpine/v3.18/community'
        state: present
        backup: yes

    - name: Update APK package cache
      apk:
        update_cache: yes

    - name: Install Cloud-init
      apk:
        name: cloud-init
        state: present

    - name: Setup Cloud-init
      command: setup-cloud-init
