---
- name: Configure Cloud-init on localhost
  hosts: localhost
  become: true
  tasks:
    - name: Update APK package cache
      apk:
        update_cache: yes

    - name: Install Cloud-init
      apk:
        name: cloud-init
        state: present

    - name: Setup Cloud-init
      command: setup-cloud-init
