---
- name: Host ISO and mount it
  hosts: localhost
  become: true
  tasks:
    - name: Create directory for ISO
      file:
        path: /srv/tftp/iso
        state: directory

    - name: Create directory for ISO mount
      file:
        path: /srv/isoubuntu
        state: directory

    - name: Mount ISO file
      mount:
        path: /srv/isoubuntu
        src: /srv/tftp/iso/ubuntu-20.04.6-live-server-amd64.iso
        fstype: iso9660
        opts: loop,ro
        state: mounted

    - name: List contents of the mounted ISO
      shell: ls /srv/isoubuntu

- name: Copy Ubuntu Casper images
  hosts: localhost
  tasks:
    - name: Create Ubuntu directory structure
      file:
        path: "/srv/tftp/ubuntu/casper"
        state: directory
        mode: 0755

    - name: Copy vmlinuz to TFTP server
      copy:
        src: "/srv/isoubuntu/casper/vmlinuz"
        dest: "/srv/tftp/ubuntu/casper/vmlinuz"
        mode: 0644

    - name: Copy initrd to TFTP server
      copy:
        src: "/srv/isoubuntu/casper/initrd"
        dest: "/srv/tftp/ubuntu/casper/initrd"
        mode: 0644