
- name: Copy kubeconfig from master1 to ansible server
  hosts: master1
  tasks:
    - name: Fetch kubeconfig
      fetch:
        src: "/etc/rancher/k3s/k3s.yaml"
        dest: "./ctx-{{ hostvars['loadbalancer'].kubernetes_cluster_name }}.yaml"
        flat: yes

- name: Update kubeconfig
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Get Load Balancer Hostname and Cluster Name
      set_fact:
        lb_hostname: "{{ groups['lb'][0] }}"
        cluster_name: "{{ hostvars['loadbalancer'].kubernetes_cluster_name }}"

    - name: Replace name and IP in kubeconfig
      replace:
        path: "./ctx-{{ hostvars['loadbalancer'].kubernetes_cluster_name }}.yaml"
        regexp: "https://127.0.0.1:6443"
        replace: "https://{{ lb_hostname }}:6443"
      delegate_to: localhost

    - name: Read k3s.yaml
      slurp:
        path: "./ctx-{{ hostvars['loadbalancer'].kubernetes_cluster_name }}.yaml"
      register: k3s_yaml_content

    - name: Update k3s.yaml with cluster name
      set_fact:
        k3s_yaml: "{{ k3s_yaml_content.content | b64decode | from_yaml }}"
     
    - name: update cluster info
      set_fact:
        k3s_yaml: "{{ k3s_yaml | default({'clusters': []}) | combine({'clusters': [{'name': hostvars['loadbalancer'].kubernetes_cluster_name , 'cluster': {'certificate-authority-data': k3s_yaml.clusters[0].cluster['certificate-authority-data'], 'server': k3s_yaml.clusters[0].cluster['server']}}]}, recursive=True) }}"
   

    - name: update user info
      set_fact:
        k3s_yaml: "{{ k3s_yaml | combine({'users': [{'name': hostvars['loadbalancer'].kubernetes_cluster_name + '-default-user', 'user': {'client-certificate-data': k3s_yaml.users[0].user['client-certificate-data'], 'client-key-data': k3s_yaml.users[0].user['client-key-data'] }}]}) }}"


    - name: Update contexts info
      set_fact:
        k3s_yaml: "{{ k3s_yaml | combine({'contexts': [{'context': {'cluster': hostvars['loadbalancer'].kubernetes_cluster_name, 'user': hostvars['loadbalancer'].kubernetes_cluster_name + '-default-user'}, 'name': 'ctx-' + hostvars['loadbalancer'].kubernetes_cluster_name}]} ) }}"

    - name: Update current-context
      set_fact:
        k3s_yaml: "{{ k3s_yaml | combine({'current-context': 'ctx-' + hostvars['loadbalancer'].kubernetes_cluster_name}) }}"


    - name: Write updated k3s.yaml
      copy:
        content: "{{ k3s_yaml | to_nice_yaml(indent=2) }}"
        dest: "./ctx-{{ hostvars['loadbalancer'].kubernetes_cluster_name }}.yaml"

